Repository hypothesis/viahtml, pull requests merged in 2020-10, with the labels that each got.

#12 Build the static items directly in the docker image
  Dockerfile
  Makefile
  requirements.in
  requirements.txt
Labels: bug

#15 Jenkinsfile update
  Jenkinsfile
Labels: added to sprint, ops

#16 Turns out there are millions of pywb headers, block them all
  tests/unit/viahtml/hooks/_headers_test.py
  viahtml/hooks/_headers.py
Labels: added to sprint, bug

#17 Use a different port so we don't clash with Via 3
  conf/development.ini
  conf/nginx/viahtml_dev/app_upstream.conf
Labels: tech debt

#19 Nest in the static content to make room for root content
  .gitignore
  bin/build_static.py
  conf/nginx/nginx.conf
  static/static/css/wrapper-style.css
  static/static/img/favicon.ico
  viahtml/templates/viahtml/wrapper.html.jinja2
Labels: tech debt, tech enabler

#20 Support "views" with no body and pass in the path
  tests/unit/viahtml/app_test.py
  tests/unit/viahtml/views/blocklist_test.py
  tests/unit/viahtml/views/status_test.py
  tox.ini
  viahtml/app.py
  viahtml/views/blocklist.py
  viahtml/views/status.py
Labels: tech enabler

#21 Share environment variables between tests and functests
  tests/conftest.py
  tests/functional/conftest.py
  tests/unit/conftest.py
Labels: tech debt

#24 Add the New Relic infrastructure agent
  conf/supervisord-dev.conf
  conf/supervisord.conf
  requirements-dev.in
  requirements.in
  requirements.txt
Labels: tech debt

#26 Add a run-docker command to make it easier to test the container image
  Makefile
Labels: tech debt

#27 Set the python path so the metrics script can find `viahtml`
  conf/supervisord.conf
Labels: bug

#28 Try kilobytes instead of kB to see if New Relic understands
  tests/unit/viahtml/stats_test.py
  viahtml/stats.py
Labels: bug

#29 Changed metric names to nest better and added more
  tests/unit/viahtml/stats_test.py
  viahtml/stats.py
Labels: enhancement
